import type { CommonText } from '@/types/content';

export const common: CommonText = {
  expandAbstract: 'Show Abstract',
  collapseAbstract: 'Hide Abstract',
  viewPaper: 'Paper',
  viewPDF: 'PDF',
  viewCode: 'Code',
  viewProject: 'Project',
  viewBibtex: 'BibTeX',
  viewDemo: 'Demo',
  viewOnGithub: 'GitHub',
  viewDetail: 'Detail',
  downloadCV: 'Download CV',
  present: 'Present',
  backToHome: 'Back to Home',
  notFoundTitle: 'Page Not Found',
  notFoundDescription: 'The page you are looking for does not exist.',
  heroGreeting: "Hi, I'm",
  heroDescription: 'Focused on Trustworthy AI, AIGC Detection & AI Agent Security.',
  aboutTitle: 'About Me',
  aboutContent: [
    "I'm a Computer Science M.S. student researching Trustworthy AI and AIGC content detection.",
    'I have a strong interest in AI security, multimodal learning, and agent systems, committed to developing reliable and secure AI technologies.',
    'Beyond academic research, I am passionate about open-source projects and technical community sharing.',
  ],
  researchInterestsTitle: 'Research Interests',
  publicationsTitle: 'Publications',
  publicationsSubtitle: 'Published and preprint papers',
  projectsTitle: 'Projects',
  projectsSubtitle: 'Personal and team projects',
  githubTitle: 'GitHub Repositories',
  githubSubtitle: 'Open source projects and code',
  experienceTitle: 'Education & Experience',
  experienceSubtitle: 'Academic and professional background',
  awardsTitle: 'Awards & Honors',
  awardsSubtitle: 'Awards and recognitions',
  cvTitle: 'Curriculum Vitae',
  cvSubtitle: 'View and download my CV',
  contactTitle: 'Contact',
  contactSubtitle: 'Get in touch',
  contactDescription:
    "If you're interested in my research or have collaboration ideas, feel free to reach out.",
  footerText: '© 2026 MocLab Academic. All rights reserved.',
  stars: 'Stars',
  forks: 'Forks',
};
