import type { CommonText } from '@/types/content';

export const common: CommonText = {
  expandAbstract: '展开摘要',
  collapseAbstract: '收起摘要',
  viewPaper: '论文',
  viewPDF: 'PDF',
  viewCode: '代码',
  viewProject: '项目',
  viewBibtex: 'BibTeX',
  viewDemo: '演示',
  viewOnGithub: 'GitHub',
  viewDetail: '详情',
  downloadCV: '下载 CV',
  present: '至今',
  backToHome: '返回首页',
  notFoundTitle: '页面未找到',
  notFoundDescription: '您访问的页面不存在，请返回首页。',
  heroGreeting: '你好，我是',
  heroDescription: '专注于可信 AI、AIGC 内容检测与 AI Agent 安全研究。',
  aboutTitle: '关于我',
  aboutContent: [
    '我是一名计算机科学硕士研究生，主要研究方向为可信 AI 和 AIGC 内容检测。',
    '我对 AI 安全、多模态学习和智能体系统有浓厚的兴趣，致力于开发可靠、安全的 AI 技术。',
    '在学术研究之外，我也热衷于开源项目和技术社区分享。',
  ],
  researchInterestsTitle: '研究方向',
  publicationsTitle: '学术成果',
  publicationsSubtitle: '已发表和预印本论文',
  projectsTitle: '工程项目',
  projectsSubtitle: '个人和团队项目',
  githubTitle: 'GitHub 仓库',
  githubSubtitle: '开源项目与代码',
  experienceTitle: '教育与经历',
  experienceSubtitle: '学术与职业经历',
  awardsTitle: '奖项荣誉',
  awardsSubtitle: '所获奖项与荣誉',
  cvTitle: '个人简历',
  cvSubtitle: '查看和下载个人简历',
  contactTitle: '联系方式',
  contactSubtitle: '欢迎联系交流',
  contactDescription: '如果您对我的研究感兴趣，或有任何合作意向，欢迎通过以下方式联系我。',
  footerText: '© 2026 MocLab Academic. All rights reserved.',
  stars: '星标',
  forks: '分叉',
};
